/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Dominio.Jugador;
import interfaz.MenuInicial;
import java.awt.Color;
import java.awt.Image;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author kingu
 */
public class FrmFinJuego extends javax.swing.JFrame {


    List<Jugador> jugadores;
    Jugador jugador;
    /**
     * Creates new form FrmFinJuego
     */
    public FrmFinJuego(List<Jugador> jugadores, Jugador jugador) {
        initComponents();

        this.getContentPane().setBackground(Color.BLACK);
        this.jugadores=jugadores;
        this.jugador=jugador;
        this.llenarPantalla();
    }

    public void llenarPantalla() {
        Collections.sort(jugadores, Comparator.comparingInt(Jugador::getPuntaje).reversed());
        this.lblGanador.setText(this.jugadores.get(0).getNombre());
        if(this.jugadores.get(0).getColor().equals("verde")){
            this.lblGanador.setForeground(Color.GREEN);
        }
        if(this.jugadores.get(0).getColor().equals("azul")){
            this.lblGanador.setForeground(Color.BLUE);
        }
        if(this.jugadores.get(0).getColor().equals("rojo")){
            this.lblGanador.setForeground(Color.RED);
        }
        if(this.jugadores.get(0).getColor().equals("amarillo")){
            this.lblGanador.setForeground(Color.YELLOW);
        }
        try {
            ImageIcon icono = new ImageIcon("src\\Avatares\\" + jugadores.get(0).getRutaAvatar());
            Image imagenRedimensionada = icono.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
            ImageIcon iconoRedimensionado = new ImageIcon(imagenRedimensionada);
            lblAvatarGanador.setIcon(iconoRedimensionado);
        } catch (Exception e) {
            e.printStackTrace(); // Puedes cambiar esto por un manejo más específico de la excepción
        }
        try {
            ImageIcon icono = new ImageIcon("src\\Avatares\\" + "trofeo.jpg");
            Image imagenRedimensionada = icono.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
            ImageIcon iconoRedimensionado = new ImageIcon(imagenRedimensionada);
            lblTrofeo.setIcon(iconoRedimensionado);
        } catch (Exception e) {
            e.printStackTrace(); // Puedes cambiar esto por un manejo más específico de la excepción
        }
        for (int i = 0; i < jugadores.size(); i++) {
            this.tblJugadores.setValueAt(jugadores.get(i).getNombre(), i, 0);
            this.tblJugadores.setValueAt(jugadores.get(i).getPuntaje(), i, 1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTrofeo = new javax.swing.JLabel();
        lblAvatarGanador = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblGanador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJugadores = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Fin del Juego");

        lblTrofeo.setText("Trofeo");

        lblAvatarGanador.setText("Avatar ganador");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 102));
        jLabel4.setText("Ganador:");

        lblGanador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGanador.setForeground(new java.awt.Color(0, 102, 255));
        lblGanador.setText("Jugador ganador");

        tblJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Jugador", "Puntos"
            }
        ));
        jScrollPane1.setViewportView(tblJugadores);

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 0, 51));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTrofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblGanador)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvatarGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(lblGanador))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAvatarGanador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTrofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(67, 67, 67))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        MenuInicial menu=MenuInicial.getInstance(jugador);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatarGanador;
    private javax.swing.JLabel lblGanador;
    private javax.swing.JLabel lblTrofeo;
    private javax.swing.JTable tblJugadores;
    // End of variables declaration//GEN-END:variables
}
