/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.CtrlServidor;
import Controlador.CtrlVistas;
import Modelo.Sala;
import SocketCliente.SocketCliente;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author kingu
 */
public class FrmMenu extends javax.swing.JFrame {

    CtrlVistas ctrlVistas = new CtrlVistas();
    SocketCliente socketCliente;

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu(SocketCliente socketCliente) {
        initComponents();

        this.getContentPane().setBackground(Color.BLACK);
        this.socketCliente = socketCliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnUnirse = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("Menu Principal");

        btnCrear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(204, 0, 51));
        btnCrear.setText("Crear Sala");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnUnirse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUnirse.setForeground(new java.awt.Color(204, 0, 51));
        btnUnirse.setText("Unirse a Sala");
        btnUnirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnirseActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(204, 0, 51));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUnirse)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnUnirse))
                .addGap(59, 59, 59)
                .addComponent(btnRegresar)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        ctrlVistas.startApplication();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        DlgTipoSala dlgTipoSala = new DlgTipoSala(this, true);
        dlgTipoSala.setVisible(true);

// Después de que el diálogo se cierra
        String tipoSeleccionado = dlgTipoSala.getTipoSeleccionado();

        if (tipoSeleccionado != null) {
            // Seleccionó "Publica" o "Privada"
            if (tipoSeleccionado.equals("Publica")) {
                Sala sala = this.socketCliente.crearSala(this.socketCliente.getJugador().getUsuario(), "PUBLICA");
                ctrlVistas.mostrarSala(sala, socketCliente);
                this.setVisible(false);
                this.dispose();
            } else {
                Sala sala = this.socketCliente.crearSala(this.socketCliente.getJugador().getUsuario(), "PRIVADA");
                ctrlVistas.mostrarSala(sala, socketCliente);
                this.setVisible(false);
                this.dispose();
            }
        } else {
            // Cerró el diálogo sin seleccionar nada
            System.out.println("Cerró el diálogo sin seleccionar nada.");
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnUnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnirseActionPerformed
        DlgOpciones opciones = new DlgOpciones(this, true);
        opciones.setVisible(true);

        String tipoSeleccionado = opciones.getTipoSeleccionado();

        if (tipoSeleccionado != null) {
            // Seleccionó "Publica" o "Privada"
            if (tipoSeleccionado.equals("Publica")) {
                Sala sala = this.socketCliente.unirsePublica(this.socketCliente.getJugador().getUsuario());
                if (sala != null) {
                    ctrlVistas.mostrarSala(sala, socketCliente);
                    this.setVisible(false);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "No hay salas disponibles");
                }
            } else {
                DlgCodigo dlgCodigo = new DlgCodigo(this, true);
                dlgCodigo.setVisible(true);

                String codigo = dlgCodigo.getTipoSeleccionado();

                if (codigo != null) {
                    Sala sala = this.socketCliente.unirseASala(codigo, this.socketCliente.getJugador().getUsuario());
                    if (sala != null) {
                        ctrlVistas.mostrarSala(sala, socketCliente);
                        this.setVisible(false);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "No hay ninguna sala con ese codigo");
                    }
                }else{
                    System.out.println("El codigo llego vacío");
                }
            }
        } else {
            // Cerró el diálogo sin seleccionar nada
            System.out.println("Cerró el diálogo sin seleccionar nada.");
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnUnirseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnUnirse;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
